seed: 42

output_dir: ./data/synth_dataset/brownian

image_size: [512, 512]

background_color: 0.0

aa_width: 1.5

save_metadata: true

image_types:
  - name: "brownian"
    count: 50
    shapes:
      - type: "Brownian" # Polygon outline
        count: [1, 2]
        params:
          num_steps: [100, 200]
          total_time: [2.0, 4.0]
          delta: [0.25, 0.5]
          thickness: [0.001, 0.01]
          brightness: [0.5, 1.0]