# Model configuration
model_name: Swin2SR
model_config: configs/models/swin2srX2.json
upscale: 2

# Dataset, preprocessing and postprocessing
dataset: data/DIV2K
batch_size: 16
num_workers: 4
first_crop: 256
second_crop: 64

# Training
num_iterations: 5000
lr: 1e-3
max_grad_norm: 1.0
save_every: 50
output_dir: checkpoints
report_scalar_rate: 5
report_image_rate: 25
